import { useState, useEffect, useRef, useCallback } from "react";
import {
  Shield, Mic, MicOff, Send, Package,
  Receipt, AlertTriangle, CheckCircle2, LogOut, TrendingUp,
  CircleDollarSign, Users, Sparkles, FileDown, Upload,
  ArrowRight, Loader2, Clock, BarChart3, Sun, Moon,
  LayoutDashboard, Bot, History, ClipboardList, Pencil, Trash2, Plus,
  ChevronLeft, ChevronRight,
} from "lucide-react";
import "./App.css";

/* ─── Types ─── */
interface Item {
  name: string;
  quantity: number;
  unit_price: number;
}

interface ParsedData {
  type: string;
  customer_name: string | null;
  total_amount: number;
  amount_paid: number;
  amount_owed: number;
  items: Item[];
}

interface Transaction {
  id: number;
  type: string;
  customer_name: string | null;
  total_amount: number;
  amount_paid: number;
  amount_owed: number;
  timestamp: string;
  items?: { product_name: string; quantity: number; unit_price: number }[];
}

interface Product {
  id: number;
  name: string;
  stock_quantity: number;
  unit: string;
  cost_price: number;
  selling_price: number;
}

type SidebarView = "dashboard" | "voice" | "manual" | "transactions" | "inventory" | "companion";

const BACKEND_URL = "http://localhost:8000";

/* ─── Auth helpers ─── */
function getToken(): string | null {
  return localStorage.getItem("marketguard_token");
}
function setTokenLocal(t: string) {
  localStorage.setItem("marketguard_token", t);
}
function clearToken() {
  localStorage.removeItem("marketguard_token");
}

async function apiFetch(path: string, options: RequestInit = {}) {
  const headers: Record<string, string> = {
    ...(options.headers as Record<string, string>),
  };
  const token = getToken();
  if (token) headers["Authorization"] = `Bearer ${token}`;
  if (!(options.body instanceof FormData)) {
    headers["Content-Type"] = headers["Content-Type"] || "application/json";
  }
  const res = await fetch(`${BACKEND_URL}${path}`, { ...options, headers });
  if (res.status === 401) {
    clearToken();
    window.location.reload();
  }
  return res;
}

/* ─── PDF Export helper ─── */
function exportToPDF(title: string, headers: string[], rows: (string | number)[][]) {
  const win = window.open("", "_blank");
  if (!win) return;
  const html = `<!DOCTYPE html><html><head><title>${title}</title>
  <style>
    body{font-family:Arial,sans-serif;padding:40px;color:#1a1a1a}
    h1{font-size:20px;margin-bottom:4px}
    .sub{color:#666;font-size:12px;margin-bottom:20px}
    table{width:100%;border-collapse:collapse;font-size:13px}
    th{text-align:left;padding:8px 10px;border-bottom:2px solid #333;background:#f5f5f5;font-weight:600}
    td{padding:8px 10px;border-bottom:1px solid #e0e0e0}
    .footer{margin-top:20px;font-size:11px;color:#999;text-align:center}
  </style></head><body>
  <h1>${title}</h1>
  <div class="sub">Generated by MarketGuard — ${new Date().toLocaleDateString()}</div>
  <table><thead><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr></thead>
  <tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table>
  <div class="footer">MarketGuard — Business Intelligence for Nigerian Micro-Merchants</div>
  </body></html>`;
  win.document.write(html);
  win.document.close();
  win.print();
}

/* ─── App ─── */
export default function App() {
  const [theme, setTheme] = useState<"light" | "dark">(() => {
    return (localStorage.getItem("marketguard_theme") as "light" | "dark") || "light";
  });

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
    localStorage.setItem("marketguard_theme", theme);
  }, [theme]);

  const toggleTheme = () => setTheme((t) => (t === "light" ? "dark" : "light"));

  const [sidebarCollapsed, setSidebarCollapsed] = useState<boolean>(() => {
    return localStorage.getItem("marketguard_sidebar_collapsed") === "true";
  });

  const toggleSidebar = () => {
    setSidebarCollapsed((prev) => {
      const newVal = !prev;
      localStorage.setItem("marketguard_sidebar_collapsed", String(newVal));
      return newVal;
    });
  };

  const [token, setTokenState] = useState<string | null>(getToken());
  const [user, setUser] = useState<{ id: number; username: string; display_name: string } | null>(null);
  const [authMode, setAuthMode] = useState<"login" | "register">("login");
  const [authUsername, setAuthUsername] = useState("");
  const [authPassword, setAuthPassword] = useState("");
  const [authError, setAuthError] = useState("");
  const [authLoading, setAuthLoading] = useState(false);

  const [isRecording, setIsRecording] = useState(false);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [transcription, setTranscription] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [mode, setMode] = useState("local");
  const [sttMode, setSttMode] = useState("local");
  const [inventory, setInventory] = useState<Product[]>([]);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [parsedResult, setParsedResult] = useState<{
    transaction_id: number | null;
    parsed_data: ParsedData;
    warnings: string[];
    hallucination?: boolean;
  } | null>(null);

  const [activeView, setActiveView] = useState<SidebarView>("dashboard");

  /* ─── Manual Transaction state ─── */
  const [manualType, setManualType] = useState<"SALE" | "CREDIT" | "RESTOCK">("SALE");
  const [manualCustomer, setManualCustomer] = useState("");
  const [manualItems, setManualItems] = useState<{ name: string; quantity: number; unit_price: number }[]>([{ name: "", quantity: 1, unit_price: 0 }]);
  const [manualPaid, setManualPaid] = useState(0);
  const [manualSaving, setManualSaving] = useState(false);
  const [manualSuccess, setManualSuccess] = useState<string | null>(null);

  /* ─── Inventory CRUD state ─── */
  const [showAddProduct, setShowAddProduct] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [newProduct, setNewProduct] = useState({ name: "", stock_quantity: 0, unit: "pcs", cost_price: 0, selling_price: 0 });
  const [importFile, setImportFile] = useState<File | null>(null);

  /* Companion chat */
  const [companionInput, setCompanionInput] = useState("");
  const [companionLoading, setCompanionLoading] = useState(false);
  const [companionHistory, setCompanionHistory] = useState<{ q: string; a: string }[]>([]);
  const companionEndRef = useRef<HTMLDivElement>(null);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);

  useEffect(() => {
    fetchMode();
    if (token) {
      fetchMe();
      fetchInventory();
      fetchTransactions();
    }
  }, [token]);

  useEffect(() => {
    companionEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [companionHistory]);

  const fetchMode = async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/health`);
      const data = await res.json();
      if (data.mode) setMode(data.mode);
      if (data.stt) setSttMode(data.stt);
    } catch { /* ignore */ }
  };

  const fetchInventory = async () => {
    try {
      const res = await apiFetch("/inventory");
      setInventory(await res.json());
    } catch (err) {
      console.error("Failed to fetch inventory", err);
    }
  };

  const fetchTransactions = async () => {
    try {
      const res = await apiFetch("/transactions");
      setTransactions(await res.json());
    } catch (err) {
      console.error("Failed to fetch transactions", err);
    }
  };

  const fetchMe = async () => {
    try {
      const res = await apiFetch("/auth/me");
      if (res.ok) setUser(await res.json());
    } catch { /* ignore */ }
  };

  const doAuth = async () => {
    setAuthError("");
    if (authPassword.length < 4) {
      setAuthError("Password must be at least 4 characters");
      return;
    }
    setAuthLoading(true);
    try {
      const res = await fetch(`${BACKEND_URL}/auth/${authMode}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: authUsername, password: authPassword }),
      });
      if (!res.ok) {
        const err = await res.json();
        setAuthError(err.detail || "Authentication failed");
        return;
      }
      const data = await res.json();
      setTokenLocal(data.token);
      setTokenState(data.token);
      setUser(data.user);
    } catch {
      setAuthError("Connection failed. Is the backend running?");
    } finally {
      setAuthLoading(false);
    }
  };

  const logout = () => {
    clearToken();
    setTokenState(null);
    setUser(null);
    setTransactions([]);
    setInventory([]);
    setParsedResult(null);
    setCompanionHistory([]);
  };

  const startRecording = async () => {
    setError(null);
    audioChunksRef.current = [];
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;
      mediaRecorder.ondataavailable = (e) => {
        if (e.data.size > 0) audioChunksRef.current.push(e.data);
      };
      mediaRecorder.onstop = () => {
        const blob = new Blob(audioChunksRef.current, { type: "audio/wav" });
        setAudioUrl(URL.createObjectURL(blob));
        uploadAudio(blob);
      };
      mediaRecorder.start();
      setIsRecording(true);
    } catch {
      setError("Microphone access denied or not supported.");
    }
  };

  const stopRecording = () => {
    if (mediaRecorderRef.current && isRecording) {
      mediaRecorderRef.current.stop();
      mediaRecorderRef.current.stream.getTracks().forEach((t) => t.stop());
      setIsRecording(false);
    }
  };

  const uploadAudio = async (blob: Blob) => {
    setIsLoading(true);
    setError(null);
    const fd = new FormData();
    fd.append("file", blob, "recording.wav");
    try {
      const res = await apiFetch("/transcribe", { method: "POST", body: fd });
      if (!res.ok) throw new Error("STT server error");
      const data = await res.json();
      setTranscription(data.transcription);
    } catch {
      setError("Failed to transcribe audio. Ensure backend is running.");
    } finally {
      setIsLoading(false);
    }
  };

  const processTextIntent = async () => {
    if (!transcription.trim()) return;
    setIsLoading(true);
    setError(null);
    setParsedResult(null);
    try {
      const res = await apiFetch("/process-intent", {
        method: "POST",
        body: JSON.stringify({ text: transcription }),
      });
      const data = await res.json();
      if (!res.ok) {
        if (res.status === 429) throw new Error("AI service is at capacity. Please try again in a moment.");
        throw new Error(data.detail || "Failed to process transaction.");
      }
      setParsedResult(data);
      fetchInventory();
      fetchTransactions();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to process transaction.");
    } finally {
      setIsLoading(false);
    }
  };

  /* ─── Manual Transaction ─── */
  const submitManualTransaction = async () => {
    const validItems = manualItems.filter(it => it.name.trim() && it.quantity > 0);
    if (validItems.length === 0) { setError("Add at least one item."); return; }

    const total = validItems.reduce((s, it) => s + it.quantity * it.unit_price, 0);
    const owed = manualType === "CREDIT" ? total - manualPaid : 0;

    setManualSaving(true);
    setError(null);
    try {
      const res = await apiFetch("/transactions/manual", {
        method: "POST",
        body: JSON.stringify({
          type: manualType,
          customer_name: manualCustomer || null,
          total_amount: total,
          amount_paid: manualPaid,
          amount_owed: owed > 0 ? owed : 0,
          items: validItems,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Failed to save.");
      setManualSuccess(`Transaction saved! ID: ${data.transaction_id}`);
      setManualType("SALE");
      setManualCustomer("");
      setManualItems([{ name: "", quantity: 1, unit_price: 0 }]);
      setManualPaid(0);
      fetchInventory();
      fetchTransactions();
      setTimeout(() => setManualSuccess(null), 3000);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to save.");
    } finally {
      setManualSaving(false);
    }
  };

  /* ─── Inventory CRUD ─── */
  const saveProduct = async () => {
    if (!newProduct.name.trim()) { setError("Product name is required."); return; }
    setError(null);
    try {
      if (editingProduct) {
        await apiFetch(`/inventory/${editingProduct.id}`, {
          method: "PUT",
          body: JSON.stringify(newProduct),
        });
      } else {
        await apiFetch("/inventory/add", {
          method: "POST",
          body: JSON.stringify(newProduct),
        });
      }
      setShowAddProduct(false);
      setEditingProduct(null);
      setNewProduct({ name: "", stock_quantity: 0, unit: "pcs", cost_price: 0, selling_price: 0 });
      fetchInventory();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to save product.");
    }
  };

  const deleteProduct = async (id: number) => {
    if (!confirm("Delete this product?")) return;
    try {
      await apiFetch(`/inventory/${id}`, { method: "DELETE" });
      fetchInventory();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Failed to delete.");
    }
  };

  const startEditProduct = (p: Product) => {
    setEditingProduct(p);
    setNewProduct({ name: p.name, stock_quantity: p.stock_quantity, unit: p.unit, cost_price: p.cost_price, selling_price: p.selling_price });
    setShowAddProduct(true);
  };

  const handleImport = async () => {
    if (!importFile) return;
    setError(null);
    const fd = new FormData();
    fd.append("file", importFile);
    try {
      const res = await apiFetch("/inventory/import", { method: "POST", body: fd });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail || "Import failed.");
      alert(`Imported ${data.imported} products.` + (data.errors.length ? `\nErrors: ${data.errors.join(", ")}` : ""));
      setImportFile(null);
      fetchInventory();
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : "Import failed.");
    }
  };

  const sendCompanion = useCallback(async () => {
    const q = companionInput.trim();
    if (!q || companionLoading) return;
    setCompanionLoading(true);
    setCompanionHistory((prev) => [...prev, { q, a: "Thinking..." }]);
    setCompanionInput("");
    try {
      const res = await apiFetch("/companion", {
        method: "POST",
        body: JSON.stringify({ question: q }),
      });
      const data = await res.json();
      if (!res.ok) {
        if (res.status === 429) throw new Error("AI service is at capacity. Please try again in a moment.");
        throw new Error(data.detail || "Companion query failed");
      }
      setCompanionHistory((prev) => {
        const updated = [...prev];
        updated[updated.length - 1] = { q, a: data.answer };
        return updated;
      });
    } catch (err: unknown) {
      setCompanionHistory((prev) => {
        const updated = [...prev];
        updated[updated.length - 1] = { q, a: `Sorry, I couldn't respond. ${err instanceof Error ? err.message : ""}` };
        return updated;
      });
    } finally {
      setCompanionLoading(false);
    }
  }, [companionInput, companionLoading]);

  /* ─── Computed stats ─── */
  const totalSales = transactions
    .filter((t) => t.type === "SALE" || t.type === "CREDIT")
    .reduce((sum, t) => sum + t.total_amount, 0);
  const totalOwed = transactions.reduce((sum, t) => sum + t.amount_owed, 0);
  const transactionCount = transactions.length;

  const ThemeToggle = () => (
    <button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme">
      {theme === "light" ? <Moon size={16} /> : <Sun size={16} />}
    </button>
  );

  const sidebarItems: { id: SidebarView; icon: typeof LayoutDashboard; label: string }[] = [
    { id: "dashboard", icon: LayoutDashboard, label: "Dashboard" },
    { id: "voice", icon: Mic, label: "Voice" },
    { id: "manual", icon: Pencil, label: "Manual Entry" },
    { id: "transactions", icon: History, label: "Transactions" },
    { id: "inventory", icon: ClipboardList, label: "Inventory" },
    { id: "companion", icon: Bot, label: "AI Companion" },
  ];

  /* ─── Landing Page ─── */
  if (!token) {
    return (
      <div className="landing-page">
        <nav className="landing-nav">
          <div className="landing-logo">
            <div className="logo-mark"><Shield size={18} color="white" /></div>
            <span>MarketGuard</span>
          </div>
          <div className="landing-nav-actions">
            <ThemeToggle />
            <button className="btn btn-ghost btn-sm" onClick={() => setAuthMode("login")}>Sign In</button>
            <button className="btn btn-primary btn-sm" onClick={() => setAuthMode("register")}>Get Started</button>
          </div>
        </nav>

        <section className="landing-hero">
          <div className="hero-content">
            <div className="hero-badge"><span className="badge-dot" />Powered by Gemma 4</div>
            <h1>Your business speaks.<br /><span className="gradient-text">AI remembers.</span></h1>
            <p className="hero-desc">
              The voice-powered business assistant for Nigeria's informal economy.
              No typing. No complicated forms. Just talk naturally in English, Pidgin, or Yoruba.
            </p>
            <div className="hero-actions">
              <button className="btn btn-primary" onClick={() => setAuthMode("register")}>Start Free <ArrowRight size={16} /></button>
              <button className="btn btn-secondary" onClick={() => setAuthMode("login")}>Sign In</button>
            </div>
          </div>
          <div className="hero-visual">
            <div className="phone-mockup">
              <div className="phone-notch"><div className="phone-notch-bar" /></div>
              <div className="phone-header"><Mic size={16} />Voice Transaction</div>
              <div className="phone-body">
                <div className="phone-msg phone-msg-user">"I sell two bags of rice to Mama Ngozi for 96,000"</div>
                <div className="phone-msg phone-msg-ai success">Recorded: SALE — 2 Rice, ₦96,000. Stock updated.</div>
                <div className="phone-msg phone-msg-user">"How much did I sell today?"</div>
                <div className="phone-msg phone-msg-ai">You sold ₦152,000 today across 3 transactions.</div>
              </div>
            </div>
          </div>
        </section>

        <section className="landing-features">
          <div className="section-header"><h2>How it works</h2><p>Speak naturally. MarketGuard handles the rest.</p></div>
          <div className="features-grid">
            <div className="feature-card"><div className="feature-icon"><Mic size={20} /></div><h3>Speak Naturally</h3><p>Talk in English, Nigerian Pidgin, or Yoruba. MarketGuard understands you.</p></div>
            <div className="feature-card"><div className="feature-icon"><Pencil size={20} /></div><h3>Type It Too</h3><p>Prefer typing? Enter transactions manually with our simple form.</p></div>
            <div className="feature-card"><div className="feature-icon"><Sparkles size={20} /></div><h3>AI Processes</h3><p>Gemma 4 extracts sales, debts, restocks — no forms to fill.</p></div>
            <div className="feature-card"><div className="feature-icon"><BarChart3 size={20} /></div><h3>Instant Records</h3><p>Transactions saved, inventory updated, debts tracked — automatically.</p></div>
            <div className="feature-card"><div className="feature-icon"><AlertTriangle size={20} /></div><h3>Smart Alerts</h3><p>Get warned when you sell below cost or when customers owe you money.</p></div>
            <div className="feature-card"><div className="feature-icon"><FileDown size={20} /></div><h3>Export Reports</h3><p>Download PDF reports of your transactions and inventory anytime.</p></div>
          </div>
        </section>

        <section className="landing-demo">
          <div className="section-header"><h2>Try it now</h2><p>Click a demo account to auto-fill credentials.</p></div>
          <div className="demo-cards">
            <button type="button" className="demo-card" onClick={() => { setAuthMode("login"); setAuthUsername("trader_a"); setAuthPassword("pass1234"); window.scrollTo({ top: document.getElementById("auth-section")?.offsetTop ?? 0, behavior: "smooth" }); }}><span className="demo-user">trader_a</span><span className="demo-pass">pass1234</span></button>
            <button type="button" className="demo-card" onClick={() => { setAuthMode("login"); setAuthUsername("trader_b"); setAuthPassword("pass1234"); window.scrollTo({ top: document.getElementById("auth-section")?.offsetTop ?? 0, behavior: "smooth" }); }}><span className="demo-user">trader_b</span><span className="demo-pass">pass1234</span></button>
            <button type="button" className="demo-card" onClick={() => { setAuthMode("login"); setAuthUsername("trader_c"); setAuthPassword("pass1234"); window.scrollTo({ top: document.getElementById("auth-section")?.offsetTop ?? 0, behavior: "smooth" }); }}><span className="demo-user">trader_c</span><span className="demo-pass">pass1234</span></button>
          </div>
        </section>

        <section className="landing-auth" id="auth-section">
          <div className="card auth-card">
            <h2>{authMode === "login" ? "Welcome back" : "Create your account"}</h2>
            <p className="auth-subtitle">{authMode === "login" ? "Sign in to your workspace" : "No email needed. Just a username and password."}</p>
            {authError && <div className="error-banner"><AlertTriangle size={14} /> {authError}</div>}
            <div className="auth-fields">
              <div className="text-field"><label>Username</label><input placeholder="Enter your username" value={authUsername} onChange={(e) => setAuthUsername(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") doAuth(); }} autoFocus /></div>
              <div className="text-field"><label>Password</label><input type="password" placeholder="4+ characters" value={authPassword} onChange={(e) => setAuthPassword(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") doAuth(); }} /></div>
            </div>
            <button className="btn btn-primary btn-full" onClick={doAuth} disabled={authLoading} style={{ marginTop: 16 }}>
              {authLoading ? <Loader2 size={16} className="spin" /> : authMode === "login" ? "Sign In" : "Create Account"}
            </button>
            <p className="auth-toggle">
              {authMode === "login" ? (
                <>Don't have an account?{" "}<a onClick={() => { setAuthMode("register"); setAuthError(""); }}>Create one</a></>
              ) : (
                <>Already have an account?{" "}<a onClick={() => { setAuthMode("login"); setAuthError(""); }}>Sign in</a></>
              )}
            </p>
          </div>
        </section>

        <footer className="landing-footer">
          <p><span className="footer-brand">MarketGuard</span> — Built for Nigeria's 40 million micro-merchants</p>
          <p>Powered by Gemma 4. Hackathon MVP.</p>
        </footer>
      </div>
    );
  }

  /* ─── Sidebar + Dashboard ─── */
  return (
    <div className={`shell ${sidebarCollapsed ? "sidebar-collapsed" : ""}`}>
      {/* Sidebar */}
      <aside className={`sidebar ${sidebarCollapsed ? "collapsed" : ""}`}>
        <button
          className="sidebar-toggle"
          onClick={toggleSidebar}
          title={sidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"}
        >
          {sidebarCollapsed ? <ChevronRight size={14} /> : <ChevronLeft size={14} />}
        </button>

        <div className="sidebar-logo">
          <div className="logo-mark"><Shield size={18} color="white" /></div>
          {!sidebarCollapsed && <span className="sidebar-logo-text">MarketGuard</span>}
        </div>

        <nav className="sidebar-nav">
          {sidebarItems.map((item) => (
            <button
              key={item.id}
              className={`sidebar-item ${activeView === item.id ? "active" : ""}`}
              onClick={() => setActiveView(item.id)}
              title={sidebarCollapsed ? item.label : undefined}
            >
              <item.icon size={18} />
              {!sidebarCollapsed && <span>{item.label}</span>}
              {!sidebarCollapsed && item.id === "companion" && <span className="sidebar-badge">AI</span>}
            </button>
          ))}
        </nav>

        <div className="sidebar-footer">
          <div className="sidebar-divider" />
          {user && (
            <div className="user-chip" title={sidebarCollapsed ? user.display_name || user.username : undefined}>
              <div className="avatar">{(user.display_name || user.username)[0].toUpperCase()}</div>
              {!sidebarCollapsed && <span>{user.display_name || user.username}</span>}
            </div>
          )}
          <div className="sidebar-footer-row">
            <ThemeToggle />
            <button className="btn-ghost" onClick={logout} title="Sign out"><LogOut size={14} /></button>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className={`main-content ${sidebarCollapsed ? "collapsed" : ""}`}>
        {/* ─── Dashboard View ─── */}
        {activeView === "dashboard" && (
          <>
            <div className="page-header">
              <h2>Dashboard</h2>
              <p className="page-subtitle">Your business at a glance</p>
            </div>

            <div className="stats-row">
              <div className="stat-card">
                <div className="stat-label"><TrendingUp size={14} /> Total Sales</div>
                <div className="stat-value sale">₦{totalSales.toLocaleString()}</div>
              </div>
              <div className="stat-card">
                <div className="stat-label"><CircleDollarSign size={14} /> Outstanding</div>
                <div className="stat-value danger">₦{totalOwed.toLocaleString()}</div>
              </div>
              <div className="stat-card">
                <div className="stat-label"><Receipt size={14} /> Transactions</div>
                <div className="stat-value">{transactionCount}</div>
              </div>
              <div className="stat-card">
                <div className="stat-label"><Package size={14} /> Products</div>
                <div className="stat-value info">{inventory.length}</div>
              </div>
            </div>

            {/* Quick Actions */}
            <div className="quick-actions">
              <button className="quick-action-card" onClick={() => setActiveView("voice")}>
                <div className="qa-icon"><Mic size={24} /></div>
                <div><strong>Record Transaction</strong><span>Speak to log a sale or restock</span></div>
                <ArrowRight size={16} className="qa-arrow" />
              </button>
              <button className="quick-action-card" onClick={() => setActiveView("manual")}>
                <div className="qa-icon manual"><Pencil size={24} /></div>
                <div><strong>Manual Entry</strong><span>Type your transaction details</span></div>
                <ArrowRight size={16} className="qa-arrow" />
              </button>
              <button className="quick-action-card" onClick={() => setActiveView("companion")}>
                <div className="qa-icon companion"><Bot size={24} /></div>
                <div><strong>Ask AI Companion</strong><span>Get business advice and insights</span></div>
                <ArrowRight size={16} className="qa-arrow" />
              </button>
            </div>

            {/* Recent Transactions */}
            <div className="card">
              <div className="card-header">
                <div className="card-title"><Clock size={18} /> Recent Transactions</div>
                <button className="btn btn-ghost btn-sm" onClick={() => setActiveView("transactions")}>View all</button>
              </div>
              <div className="table-wrapper">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Time</th>
                      <th>Type</th>
                      <th>Customer</th>
                      <th className="text-right">Total</th>
                      <th className="text-right">Owed</th>
                    </tr>
                  </thead>
                  <tbody>
                    {transactions.length === 0 ? (
                      <tr><td colSpan={5} className="table-empty">No transactions yet. Record your first one!</td></tr>
                    ) : (
                      transactions.slice(0, 5).map((tx) => (
                        <tr key={tx.id}>
                          <td><Clock size={12} style={{ marginRight: 6, opacity: 0.4 }} />{new Date(tx.timestamp).toLocaleTimeString()}</td>
                          <td><span className={`badge badge-${tx.type}`}>{tx.type}</span></td>
                          <td className="text-primary">{tx.customer_name || "General"}</td>
                          <td className="text-right text-primary">₦{tx.total_amount.toLocaleString()}</td>
                          <td className={`text-right ${tx.amount_owed > 0 ? "text-danger" : ""}`}>₦{tx.amount_owed.toLocaleString()}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Low Stock Alert */}
            {inventory.filter((p) => p.stock_quantity < 5).length > 0 && (
              <div className="card warning-card">
                <div className="card-title"><AlertTriangle size={18} /> Low Stock Alert</div>
                <div className="low-stock-list">
                  {inventory.filter((p) => p.stock_quantity < 5).map((p) => (
                    <div key={p.id} className="low-stock-item">
                      <span>{p.name}</span>
                      <span className="text-danger">{p.stock_quantity} {p.unit} left</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </>
        )}

        {/* ─── Voice Recording View ─── */}
        {activeView === "voice" && (
          <>
            <div className="page-header">
              <h2>Record Transaction</h2>
              <p className="page-subtitle">Speak in Yoruba, Pidgin, or English</p>
            </div>

            <div className="voice-layout">
              <div className="card voice-card">
                <div className="voice-area">
                  <div className="mic-wrapper">
                    <button
                      className={`mic-button ${isRecording ? "recording" : ""}`}
                      onClick={isRecording ? stopRecording : startRecording}
                      disabled={isLoading}
                    >
                      {isRecording ? <MicOff size={32} /> : <Mic size={32} />}
                    </button>
                    <div className="mic-ring" />
                  </div>
                  <p className={`mic-label ${isRecording ? "recording" : ""}`}>
                    {isRecording ? "Listening... Click to stop" : isLoading ? "Processing..." : "Click to speak"}
                  </p>
                </div>

                {audioUrl && (
                  <div className="audio-player"><audio src={audioUrl} controls /></div>
                )}

                {error && <div className="error-banner"><AlertTriangle size={14} /> {error}</div>}

                {parsedResult?.hallucination && (
                  <div className="hallucination-notice">
                    <AlertTriangle size={14} />
                    <span>AI couldn't parse the transaction perfectly. Please rephrase or try again.</span>
                  </div>
                )}

                <div className="input-group">
                  <label className="input-label" htmlFor="transcription-input">Transcription</label>
                  <textarea
                    id="transcription-input"
                    className="textarea-field"
                    value={transcription}
                    onChange={(e) => setTranscription(e.target.value)}
                    placeholder="Your spoken transaction will appear here..."
                    disabled={isLoading}
                  />
                  <button className="btn btn-primary btn-full" onClick={processTextIntent} disabled={isLoading || !transcription.trim()}>
                    {isLoading ? <><Loader2 size={16} className="spin" /> Processing with Gemma...</> : <><CheckCircle2 size={16} /> Confirm & Parse Transaction</>}
                  </button>
                </div>
              </div>

              <div className="card">
                {parsedResult ? (
                  <div className="parsed-output">
                    <div className="parsed-header">
                      <h3>Transaction Decoded</h3>
                      <span className={`badge badge-${parsedResult.parsed_data.type}`}>{parsedResult.parsed_data.type}</span>
                    </div>
                    <div className="detail-grid">
                      <div className="detail-item"><span className="detail-label">Customer</span><span className="detail-value">{parsedResult.parsed_data.customer_name || "General / Cash"}</span></div>
                      <div className="detail-item"><span className="detail-label">Total Value</span><span className="detail-value highlight">₦{parsedResult.parsed_data.total_amount.toLocaleString()}</span></div>
                      <div className="detail-item"><span className="detail-label">Amount Paid</span><span className="detail-value">₦{parsedResult.parsed_data.amount_paid.toLocaleString()}</span></div>
                      <div className="detail-item"><span className="detail-label">Amount Owed</span><span className={`detail-value ${parsedResult.parsed_data.amount_owed > 0 ? "danger" : ""}`}>₦{parsedResult.parsed_data.amount_owed.toLocaleString()}</span></div>
                    </div>
                    <div className="items-section">
                      <h4>Items</h4>
                      {parsedResult.parsed_data.items.map((item, idx) => (
                        <div className="item-row" key={idx}>
                          <span className="item-name">{item.name} × {item.quantity}</span>
                          <span className="item-price">₦{(item.quantity * item.unit_price).toLocaleString()}</span>
                        </div>
                      ))}
                    </div>
                    {parsedResult.warnings && parsedResult.warnings.length > 0 ? (
                      <div className="warnings-box">
                        <h4><AlertTriangle size={14} /> Audit Alerts</h4>
                        <ul>{parsedResult.warnings.map((w, idx) => <li key={idx}>{w}</li>)}</ul>
                      </div>
                    ) : (
                      <div className="clean-audit"><CheckCircle2 size={16} /> Audit clean — prices match restock rates</div>
                    )}
                  </div>
                ) : (
                  <div className="empty-state">
                    <div className="empty-icon"><BarChart3 size={24} /></div>
                    <div className="empty-title">No transaction parsed yet</div>
                    <div className="empty-desc">Record a transaction to see AI-powered analysis here.</div>
                  </div>
                )}
              </div>
            </div>
          </>
        )}

        {/* ─── Manual Entry View ─── */}
        {activeView === "manual" && (
          <>
            <div className="page-header">
              <h2>Manual Transaction Entry</h2>
              <p className="page-subtitle">Type your transaction details directly</p>
            </div>

            <div className="card">
              {manualSuccess && <div className="success-banner"><CheckCircle2 size={14} /> {manualSuccess}</div>}
              {error && <div className="error-banner"><AlertTriangle size={14} /> {error}</div>}

              <div className="form-grid">
                <div className="text-field">
                  <label>Transaction Type</label>
                  <select value={manualType} onChange={(e) => setManualType(e.target.value as "SALE" | "CREDIT" | "RESTOCK")}>
                    <option value="SALE">SALE</option>
                    <option value="CREDIT">CREDIT</option>
                    <option value="RESTOCK">RESTOCK</option>
                  </select>
                </div>
                <div className="text-field">
                  <label>Customer Name {manualType === "CREDIT" && <span className="required">*</span>}</label>
                  <input placeholder="e.g. Mama Ngozi" value={manualCustomer} onChange={(e) => setManualCustomer(e.target.value)} />
                </div>
              </div>

              <div className="items-header">
                <h4>Items</h4>
                <button className="btn btn-ghost btn-sm" onClick={() => setManualItems([...manualItems, { name: "", quantity: 1, unit_price: 0 }])}>
                  <Plus size={14} /> Add Item
                </button>
              </div>

              {manualItems.map((item, idx) => (
                <div className="item-input-row" key={idx}>
                  <input
                    className="item-field item-name-input"
                    placeholder="Product name"
                    value={item.name}
                    onChange={(e) => {
                      const updated = [...manualItems];
                      updated[idx].name = e.target.value;
                      setManualItems(updated);
                    }}
                  />
                  <input
                    className="item-field item-qty-input"
                    type="number"
                    min="0"
                    placeholder="Qty"
                    value={item.quantity}
                    onChange={(e) => {
                      const updated = [...manualItems];
                      updated[idx].quantity = Number(e.target.value);
                      setManualItems(updated);
                    }}
                  />
                  <input
                    className="item-field item-price-input"
                    type="number"
                    min="0"
                    placeholder="Unit Price (₦)"
                    value={item.unit_price}
                    onChange={(e) => {
                      const updated = [...manualItems];
                      updated[idx].unit_price = Number(e.target.value);
                      setManualItems(updated);
                    }}
                  />
                  <span className="item-total">₦{(item.quantity * item.unit_price).toLocaleString()}</span>
                  {manualItems.length > 1 && (
                    <button className="btn-icon" onClick={() => setManualItems(manualItems.filter((_, i) => i !== idx))}>
                      <Trash2 size={14} />
                    </button>
                  )}
                </div>
              ))}

              <div className="form-grid" style={{ marginTop: 16 }}>
                <div className="text-field">
                  <label>Amount Paid (₦)</label>
                  <input type="number" min="0" value={manualPaid} onChange={(e) => setManualPaid(Number(e.target.value))} />
                </div>
                <div className="text-field">
                  <label>Total</label>
                  <div className="static-value">₦{manualItems.reduce((s, it) => s + it.quantity * it.unit_price, 0).toLocaleString()}</div>
                </div>
              </div>

              <button className="btn btn-primary btn-full" onClick={submitManualTransaction} disabled={manualSaving} style={{ marginTop: 16 }}>
                {manualSaving ? <><Loader2 size={16} className="spin" /> Saving...</> : <><CheckCircle2 size={16} /> Save Transaction</>}
              </button>
            </div>
          </>
        )}

        {/* ─── Transactions View ─── */}
        {activeView === "transactions" && (
          <>
            <div className="page-header">
              <h2>Transaction History</h2>
              <p className="page-subtitle">All recorded transactions</p>
            </div>
            <div className="card">
              <div className="card-header">
                <div />
                <button className="btn btn-ghost btn-sm" onClick={() => {
                  const headers = ["Time", "Type", "Customer", "Total", "Paid", "Owed"];
                  const rows = transactions.map(tx => [
                    new Date(tx.timestamp).toLocaleString(),
                    tx.type,
                    tx.customer_name || "General",
                    `₦${tx.total_amount.toLocaleString()}`,
                    `₦${tx.amount_paid.toLocaleString()}`,
                    `₦${tx.amount_owed.toLocaleString()}`,
                  ]);
                  exportToPDF("Transaction Report", headers, rows);
                }}><FileDown size={14} /> Export PDF</button>
              </div>
              <div className="table-wrapper">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Time</th>
                      <th>Type</th>
                      <th>Customer</th>
                      <th>Items</th>
                      <th className="text-right">Total</th>
                      <th className="text-right">Paid</th>
                      <th className="text-right">Owed</th>
                    </tr>
                  </thead>
                  <tbody>
                    {transactions.length === 0 ? (
                      <tr><td colSpan={7} className="table-empty">No transactions recorded yet.</td></tr>
                    ) : (
                      transactions.map((tx) => (
                        <tr key={tx.id}>
                          <td><Clock size={12} style={{ marginRight: 6, opacity: 0.4 }} />{new Date(tx.timestamp).toLocaleString()}</td>
                          <td><span className={`badge badge-${tx.type}`}>{tx.type}</span></td>
                          <td className="text-primary">{tx.customer_name || "General"}</td>
                          <td>{tx.items?.map((it) => `${it.product_name} (${it.quantity})`).join(", ") || "—"}</td>
                          <td className="text-right text-primary">₦{tx.total_amount.toLocaleString()}</td>
                          <td className="text-right">₦{tx.amount_paid.toLocaleString()}</td>
                          <td className={`text-right ${tx.amount_owed > 0 ? "text-danger" : ""}`}>₦{tx.amount_owed.toLocaleString()}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </>
        )}

        {/* ─── Inventory View ─── */}
        {activeView === "inventory" && (
          <>
            <div className="page-header">
              <h2>Product Inventory</h2>
              <p className="page-subtitle">Stock levels and cost baselines</p>
            </div>

            <div className="card-header-row">
              <button className="btn btn-primary btn-sm" onClick={() => { setEditingProduct(null); setNewProduct({ name: "", stock_quantity: 0, unit: "pcs", cost_price: 0, selling_price: 0 }); setShowAddProduct(true); }}>
                <Plus size={14} /> Add Product
              </button>
              <div className="import-row">
                <label className="btn btn-ghost btn-sm" style={{ cursor: "pointer" }}>
                  <Upload size={14} /> Import CSV/JSON
                  <input type="file" accept=".csv,.json" style={{ display: "none" }} onChange={(e) => setImportFile(e.target.files?.[0] || null)} />
                </label>
                {importFile && (
                  <button className="btn btn-primary btn-sm" onClick={handleImport}>Upload {importFile.name}</button>
                )}
                <button className="btn btn-ghost btn-sm" onClick={() => {
                  const headers = ["Product", "Stock", "Unit", "Cost Price", "Selling Price"];
                  const rows = inventory.map(p => [p.name, p.stock_quantity, p.unit, `₦${p.cost_price.toLocaleString()}`, `₦${p.selling_price.toLocaleString()}`]);
                  exportToPDF("Inventory Report", headers, rows);
                }}><FileDown size={14} /> Export PDF</button>
              </div>
            </div>

            {/* Add/Edit Product Modal */}
            {showAddProduct && (
              <div className="modal-overlay" onClick={() => { setShowAddProduct(false); setEditingProduct(null); }}>
                <div className="card modal-card" onClick={(e) => e.stopPropagation()}>
                  <h3>{editingProduct ? "Edit Product" : "Add New Product"}</h3>
                  <div className="form-grid">
                    <div className="text-field"><label>Product Name</label><input value={newProduct.name} onChange={(e) => setNewProduct({ ...newProduct, name: e.target.value })} placeholder="e.g. Rice" /></div>
                    <div className="text-field"><label>Stock Quantity</label><input type="number" min="0" value={newProduct.stock_quantity} onChange={(e) => setNewProduct({ ...newProduct, stock_quantity: Number(e.target.value) })} /></div>
                    <div className="text-field"><label>Unit</label><input value={newProduct.unit} onChange={(e) => setNewProduct({ ...newProduct, unit: e.target.value })} placeholder="e.g. bag, pcs, litre" /></div>
                    <div className="text-field"><label>Cost Price (₦)</label><input type="number" min="0" value={newProduct.cost_price} onChange={(e) => setNewProduct({ ...newProduct, cost_price: Number(e.target.value) })} /></div>
                    <div className="text-field"><label>Selling Price (₦)</label><input type="number" min="0" value={newProduct.selling_price} onChange={(e) => setNewProduct({ ...newProduct, selling_price: Number(e.target.value) })} /></div>
                  </div>
                  <div className="modal-actions">
                    <button className="btn btn-ghost" onClick={() => { setShowAddProduct(false); setEditingProduct(null); }}>Cancel</button>
                    <button className="btn btn-primary" onClick={saveProduct}>{editingProduct ? "Update" : "Add"}</button>
                  </div>
                </div>
              </div>
            )}

            <div className="card">
              <div className="table-wrapper">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Product</th>
                      <th className="text-right">Stock</th>
                      <th>Unit</th>
                      <th className="text-right">Cost Price</th>
                      <th className="text-right">Selling Price</th>
                      <th className="text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {inventory.length === 0 ? (
                      <tr><td colSpan={6} className="table-empty">No products in inventory yet.</td></tr>
                    ) : (
                      inventory.map((prod) => (
                        <tr key={prod.id}>
                          <td className="text-primary">{prod.name}</td>
                          <td className={`text-right ${prod.stock_quantity < 5 ? "text-danger" : ""}`}>{prod.stock_quantity}</td>
                          <td>{prod.unit}</td>
                          <td className="text-right">₦{prod.cost_price.toLocaleString()}</td>
                          <td className="text-right">₦{prod.selling_price.toLocaleString()}</td>
                          <td className="text-right">
                            <button className="btn-icon" onClick={() => startEditProduct(prod)}><Pencil size={14} /></button>
                            <button className="btn-icon danger" onClick={() => deleteProduct(prod.id)}><Trash2 size={14} /></button>
                          </td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </>
        )}

        {/* ─── AI Companion View ─── */}
        {activeView === "companion" && (
          <>
            <div className="page-header">
              <h2>AI Companion</h2>
              <p className="page-subtitle">Your personal business advisor</p>
            </div>

            <div className="companion-layout">
              <div className="card companion-card">
                {companionHistory.length === 0 ? (
                  <div className="companion-welcome">
                    <div className="companion-avatar-large"><Bot size={40} /></div>
                    <h3>Hi! I'm your MarketGuard AI Companion</h3>
                    <p>Ask me anything about your business — pricing strategy, debt management, inventory tips, or just for encouragement.</p>
                    <div className="companion-suggestions">
                      <button className="suggestion-chip" onClick={() => { setCompanionInput("What should I do about customers who owe me money?"); }}>
                        <CircleDollarSign size={14} /> Debt management tips
                      </button>
                      <button className="suggestion-chip" onClick={() => { setCompanionInput("How can I increase my sales this week?"); }}>
                        <TrendingUp size={14} /> Boost my sales
                      </button>
                      <button className="suggestion-chip" onClick={() => { setCompanionInput("What products should I restock?"); }}>
                        <Package size={14} /> Restock advice
                      </button>
                      <button className="suggestion-chip" onClick={() => { setCompanionInput("Give me a motivation to keep going!"); }}>
                        <Sparkles size={14} /> Motivate me
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="companion-messages">
                    {companionHistory.map((msg, idx) => (
                      <div className="chat-msg-group" key={idx}>
                        <div className="chat-bubble chat-bubble-user"><Users size={12} style={{ marginRight: 6, opacity: 0.7 }} />{msg.q}</div>
                        <div className="chat-bubble chat-bubble-ai"><Bot size={12} style={{ marginRight: 6, opacity: 0.5 }} />{msg.a}</div>
                      </div>
                    ))}
                    <div ref={companionEndRef} />
                  </div>
                )}

                <div className="companion-input-row">
                  <input
                    className="chat-input"
                    value={companionInput}
                    onChange={(e) => setCompanionInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter") sendCompanion(); }}
                    placeholder="Ask your AI companion..."
                    disabled={companionLoading}
                  />
                  <button className="btn btn-primary" onClick={sendCompanion} disabled={companionLoading || !companionInput.trim()}>
                    {companionLoading ? <Loader2 size={16} className="spin" /> : <Send size={16} />}
                  </button>
                </div>
              </div>
            </div>
          </>
        )}
      </main>

      <style>{`
        .spin { animation: spin 1s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}
